spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${SERVER_PORT:8081}
spring.application.name=notification-adapter

# Automated Simulation Push Scheduler Settings
simulator.scheduler.enabled=${SCHEDULER_ENABLED:false}
simulator.scheduler.fixed-rate-ms=${SCHEDULER_RATE_MS:60000}
simulator.adapter-url=${NOTIFICATION_ADAPTER_URL:http://localhost:8081/api/v1/events/ingest}
simulator.profile-name=${SCHEDULER_PROFILE_NAME:COVERAGE_ALERT_RANDOM_DOMAINS}

app.kafka.topics.report-created=network.report.created
