spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${ADAPTER_DB_NAME:${INGEST_DB_NAME:adapter_db}}?stringtype=unspecified
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgrespassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


# Cấu hình kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer 
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.retries=10
spring.kafka.producer.properties.retry.backoff.ms=1000
spring.kafka.producer.properties.delivery.timeout.ms=30000
spring.kafka.producer.properties.request.timeout.ms=10000
notification.adapter.result-consumer.group-id=${ADAPTER_RESULT_CONSUMER_GROUP:notification-adapter-result-group}

# Cấu hình service
scheduler.batch.enabled=true
scheduler.profile.enabled=true
scheduler.profile.scan-cron=0 * * * * *
scheduler.profile.zone=Asia/Ho_Chi_Minh
scheduler.batch.fixed-delay=10000
scheduler.batch.size=${ADAPTER_PUBLISH_BATCH_SIZE:20}
mini-business.service.url=http://${MINI_BUSINESS_HOST:localhost}:${MINI_BUSINESS_PORT:8080}
