spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${SERVER_PORT:8087}
spring.application.name=ott-worker

app.kafka.topics.ott-task=delivery.ott.v1
telegram.bot-token=${TELEGRAM_BOT_TOKEN:}
telegram.default-chat-id=${TELEGRAM_CHAT_ID:}
spring.servlet.multipart.max-file-size=${TELEGRAM_TEST_MAX_FILE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${TELEGRAM_TEST_MAX_FILE_SIZE:20MB}
