spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${SERVER_PORT:8084}
spring.application.name=email-worker

app.kafka.topics.email-task=delivery.email.v1
app.report.storage.base-path=${REPORT_STORAGE_PATH:./data/reports}
